server:
  port: 9191


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: Hybris123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl